### ISSUE TITLE
提2个建议

### ISSUE THREAD

**Issue by gdfyj90** [Arc-lin/ALCalendarPicker#2]
1 UIView (Frame)这个拓展估计很多朋友自己也有的，建议你名字加下前缀
2 左右滑动之后建议通过代理返回当前页面的年份月份，因为有时候像签到功能，不可能返回全部已签到的数据，而是滑动之后需要向后台请求对应月份的数据

**Comment by Arc-lin** [comment]
谢谢你的建议, 我已经更新了框架了, 但是目前由于某些原因还不能发布到pod, 你可以先看看github的源码哟~

**Comment by Arc-lin** [comment]
pod已更新
