### ISSUE TITLE
关于cell添加事件badge红点。

### ISSUE THREAD

**Issue by Just013** [Arc-lin/ALCalendarPicker#3]
你好，遇到个订制的需求，需要将cell按照接口返回的事件时间来添加小红点角标，目前在修改你的源码。不知道应该从config入手？ 还是应该从date入手？
![default](https://user-images.githubusercontent.com/16714101/51081231-c651f700-1725-11e9-9125-feeef9c2c988.png)
我从config入手，出现了小红点不在指定时间事件cell上，而是乱跑的情况。
求助

**Comment by Arc-lin** [comment]
乱跑有两种情况，一种是cell里面小红点的布局没弄好，另一种是cell复用问题，当不需要小红点的时候hidden = YES，需要的时候 hidden = NO.
另外看你的截图，你应该是在cellForItemAtIndexPath 里面 addSubView了吧， 其实这种操作很危险，一不小心就会在同个位置上叠加多个小红点，还是在cell里先备好一个小红点，然后根据情况赋值角标数字还有显示隐藏吧。
